apiVersion: apps/v1
kind: Deployment
metadata:
  name: inditex-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inditex-app
  template:
    metadata:
      labels:
        app: inditex-app
    spec:
      containers:
        - name: inditex-app
          image: jailucloz/inditex-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080