apiVersion: v1
kind: Service
metadata:
  name: inditex-service
spec:
  type: NodePort
  selector:
    app: inditex-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30005